### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Weblate](https://hosted.weblate.org/projects/eventol/django/) for eventoL/Django.

Current translation status:

Weblate translation status

### CODE REVIEW

**Review by FedeG — APPROVED** [review]

**Comment by FedeG** [comment]
Thanks @Vistaus and @NathanBnm

@NathanBnm, I usually add all contributors to the readme file (contributors section), do you have a problem with it?

**Comment by NathanBnm** [comment]
@FedeG I have no problem with this 😉

**Comment by Vistaus** [comment]
You may add me as well 🙂

**Review by FedeG — APPROVED** [review]

**Comment by FedeG** [comment]
> @FedeG I have no problem with this wink

@all-contributors please add @NathanBnm for translation

**Pull request merged**
